### ISSUE TITLE
Fails to build with vala 0.46

### ISSUE THREAD

**Issue by worldofpeace** [davidmhewitt/torrential#135]
## Build Log
```
[ 86%] Generating src/Application.c;src/MainWindow.c;src/PreferencesWindow.c;src/TorrentManager.c;src/Torrent.c;src/Settings.c;src/Dialogs/FileSelectDialog.c;src/Widgets/FileSelectTreeView.c;src/Widgets/MultiInfoBar.c;src/Widgets/TorrentListBox.c;src/Widgets/TorrentListRow.c
/build/source/src/TorrentManager.vala:77.9-77.25: warning: delegates with scope="async" must be owned
        ThreadFunc<void*> run = () => {
        ^^^^^^^^^^^^^^^^^
Compilation failed: 0 error(s), 1 warning(s)`
```

## System Info
OS: NixOS 20.03
Vala: 0.46.1
GLib: 2.62.0
GTK: 3.24.11
Torrential: 1.1.0

**Comment by worldofpeace** [comment]
This has been an issue before vala 0.46, I can reproduce with 0.44 as well.

**Comment by khurshid-alam** [comment]
@davidmhewitt Can you fix it for vala >= 0.46 ?
