### ISSUE TITLE
Fail to build with transmission 4.0.0

### ISSUE THREAD

**Issue by bobby285271** [davidmhewitt/torrential#193]
Building 2.0.1 and/or current HEAD commit (2e22a8b) with transmission 4.0.0 fails with:

```
In file included from /nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/transmission.h:23,
                 from src/com.github.davidmhewitt.torrential.p/Dialogs/FileSelectDialog.c:32:
/nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/tr-macros.h:8:10: fatal error: array: No such file or directory
    8 | #include <array>
      |          ^~~~~~~
compilation terminated.
```

A full log here:

<details>

```
this derivation will be built:
  /nix/store/2ywr1xdgcl90rgbi8m1qfkcdbj03zks1-torrential-2.0.1.drv
building '/nix/store/2ywr1xdgcl90rgbi8m1qfkcdbj03zks1-torrential-2.0.1.drv'...
unpacking sources
unpacking source archive /nix/store/n4bxn959iyz27w6gyz3w5pxbkr8sd24j-source
source root is source
patching sources
patching script interpreter paths in meson/post_install.py
meson/post_install.py: interpreter directive changed from "#!/usr/bin/env python3" to "/nix/store/0pyymzxf7n0fzpaqnvwv92ab72v3jq8d-python3-3.10.9/bin/python3"
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/lib --libexecdir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/libexec         --bindir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/bin --sbindir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/sbin         --includedir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/include         --mandir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/share/man --infodir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/share/info         --localedir=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1  
The Meson build system
Version: 1.0.0
Source dir: /build/source
Build dir: /build/source/build
Build type: native build
Project name: com.github.davidmhewitt.torrential
Project version: 2.0.1
C compiler for the host machine: gcc (gcc 12.2.0 "gcc (GCC) 12.2.0")
C linker for the host machine: gcc ld.bfd 2.40
Vala compiler for the host machine: valac (valac 0.56.3)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /nix/store/lrb01sby9jg4hfqhr32s28igg77bhcwr-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency gtk+-3.0 found: YES 3.24.36
Run-time dependency gee-0.8 found: YES 0.20.6
Run-time dependency granite found: YES 6.2.0
Run-time dependency threads found: YES
Library posix found: YES
Library transmission-2.0 found: YES
Library transmission found: YES
Library b64 found: YES
Library dht found: YES
Library miniupnpc found: YES
Library natpmp found: YES
Library utp found: YES
Library event found: YES
Library curl found: YES
Library ssl found: YES
Library crypto found: YES
Program msgfmt found: YES (/nix/store/nzxhm7b91pbjq7m8j5a1dwvpy2ib5pql-gettext-0.21/bin/msgfmt)
Found pkg-config: /nix/store/lrb01sby9jg4hfqhr32s28igg77bhcwr-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/bin/glib-compile-resources)
Configuring Config.vala using configuration
Program msginit found: YES (/nix/store/nzxhm7b91pbjq7m8j5a1dwvpy2ib5pql-gettext-0.21/bin/msginit)
Program msgmerge found: YES (/nix/store/nzxhm7b91pbjq7m8j5a1dwvpy2ib5pql-gettext-0.21/bin/msgmerge)
Program xgettext found: YES (/nix/store/nzxhm7b91pbjq7m8j5a1dwvpy2ib5pql-gettext-0.21/bin/xgettext)
Build targets in project: 31

com.github.davidmhewitt.torrential 2.0.1

  User defined options
    auto_features: enabled
    bindir       : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/bin
    buildtype    : plain
    includedir   : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/include
    infodir      : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/share/info
    libdir       : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/lib
    libexecdir   : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/libexec
    localedir    : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/share/locale
    mandir       : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/share/man
    prefix       : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1
    sbindir      : /nix/store/wpxnlf3x9dzbyw5s49az1bmkvfij7yj9-torrential-2.0.1/sbin
    wrap_mode    : nodownload

Found ninja-1.11.1 at /nix/store/7q3dwpp97lxsy3zpjdcyl99rhk46f0cp-ninja-1.11.1/bin/ninja
meson: enabled parallel building
building
build flags: -j8
[1/29] Generating data/gresource_icons_h with a custom command
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
[2/29] Generating po/de/LC_MESSAGES/com.github.davidmhewitt.torrential-de.mo with a custom command
[3/29] Generating po/es/LC_MESSAGES/com.github.davidmhewitt.torrential-es.mo with a custom command
[4/29] Generating data/gresource_icons_c with a custom command
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
[5/29] Generating po/fr/LC_MESSAGES/com.github.davidmhewitt.torrential-fr.mo with a custom command
[6/29] Generating po/fr_CA/LC_MESSAGES/com.github.davidmhewitt.torrential-fr_CA.mo with a custom command
[7/29] Generating po/it/LC_MESSAGES/com.github.davidmhewitt.torrential-it.mo with a custom command
[8/29] Generating po/id/LC_MESSAGES/com.github.davidmhewitt.torrential-id.mo with a custom command
[9/29] Generating po/lt/LC_MESSAGES/com.github.davidmhewitt.torrential-lt.mo with a custom command
[10/29] Generating po/pt_BR/LC_MESSAGES/com.github.davidmhewitt.torrential-pt_BR.mo with a custom command
[11/29] Generating po/nl/LC_MESSAGES/com.github.davidmhewitt.torrential-nl.mo with a custom command
[12/29] Generating po/ru/LC_MESSAGES/com.github.davidmhewitt.torrential-ru.mo with a custom command
[13/29] Generating data/com.github.davidmhewitt.torrential.desktop with a custom command
[14/29] Generating data/com.github.davidmhewitt.torrential.appdata.xml with a custom command
[15/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_.._.._data_gresource_icons.c.o
[16/29] Compiling Vala source ../src/Dialogs/FileSelectDialog.vala ../src/Widgets/FileSelectTreeView.vala ../src/Widgets/MultiInfoBar.vala ../src/Widgets/TorrentListBox.vala ../src/Widgets/TorrentListRow.vala ../src/Application.vala ../src/MainWindow.vala ../src/PreferencesWindow.vala ../src/Settings.vala ../src/Torrent.vala ../src/TorrentManager.vala src/Config.vala
/build/source/vapi/transmission-2.0.vapi:2051.4-2051.8: warning: Argument `header_filename' never used
 2051 |                 [CCode (header_filename = "transmission/utils.h", cname = "tr_torerr")]
      |                  ^~~~~                                                                 
/build/source/vapi/transmission-2.0.vapi:2054.4-2054.8: warning: Argument `header_filename' never used
 2054 |                 [CCode (header_filename = "transmission/utils.h", cname = "tr_torinf")]
      |                  ^~~~~                                                                 
/build/source/vapi/transmission-2.0.vapi:2057.4-2057.8: warning: Argument `header_filename' never used
 2057 |                 [CCode (header_filename = "transmission/utils.h", cname = "tr_tordbg")]
      |                  ^~~~~                                                                 
/build/source/vapi/transmission-2.0.vapi:491.28-491.32: warning: Argument `array_lengh_type' never used
  491 |                 public static int load ([CCode (array_lengh_type = "size_t")] uint8[] buf, out variant variant, out unowned uint8[] end);
      |                                          ^~~~~                                                                                           
/build/source/vapi/transmission-2.0.vapi:494.24-494.28: warning: Argument `array_lengh_type' never used
  494 |                 public variant.str ([CCode (array_lengh_type = "int")] char[] raw);
      |                                      ^~~~~                                         
/build/source/vapi/transmission-2.0.vapi:496.24-496.28: warning: Argument `array_lengh_type' never used
  496 |                 public variant.raw ([CCode (array_lengh_type = "size_t")] uint8[] raw);
      |                                      ^~~~~                                             
/build/source/vapi/transmission-2.0.vapi:532.25-532.29: warning: Argument `array_lengh_type' never used
  532 |                 public bool get_raw ([CCode (array_lengh_type = "size_t")] out uint8[] raw);
      |                                       ^~~~~                                                 
/build/source/vapi/transmission-2.0.vapi:580.39-580.43: warning: Argument `array_lengh_type' never used
  580 |                 public unowned variant ListAddRaw ([CCode (array_lengh_type = "size_t")] uint8[] val);
      |                                                     ^~~~~                                             
/build/source/vapi/transmission-2.0.vapi:617.48-617.52: warning: Argument `array_lengh_type' never used
  617 |                 public unowned variant? add_raw (Prefs key, [CCode (array_lengh_type = "size_t")] uint8[] raw);
      |                                                              ^~~~~                                             
/build/source/vapi/transmission-2.0.vapi:635.37-635.41: warning: Argument `array_lengh_type' never used
  635 |                 public bool find_raw (Prefs key, [CCode (array_lengh_type = "size_t")] out uint8[]? raw);
      |                                                   ^~~~~                                                  
Compilation succeeded - 10 warning(s)
[17/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListRow.c.o
FAILED: src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListRow.c.o 
gcc -Isrc/com.github.davidmhewitt.torrential.p -Isrc -I../src -Idata -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/glib-2.0 -I/nix/store/jzh15bi6zablx3d9s928w3lgqy6and91-glib-2.74.3/lib/glib-2.0/include -I/nix/store/yb0miyl7hgl9jcrni8qhykdaa747si35-gtk+3-3.24.36-dev/include/gtk-3.0 -I/nix/store/4zh493xqn3zmbbp2769xr6lr1klii7ff-at-spi2-core-2.46.0-dev/include/atk-1.0 -I/nix/store/mvhiwg7wkacdmi6p6j1sb3sm4ww3mq6z-cairo-1.16.0-dev/include/cairo -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include/freetype2 -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include -I/nix/store/ckd2dal5674yjgwdcf0lpqyxn19g4mdk-gdk-pixbuf-2.42.10-dev/include/gdk-pixbuf-2.0 -I/nix/store/vffghgqfw7md3jg7qclnbfy2afzri65l-pango-1.50.12-dev/include/pango-1.0 -I/nix/store/bd3x5n8mrmhz65c81xi8m669kixhgp7v-harfbuzz-6.0.0-dev/include/harfbuzz -I/nix/store/6v8jpxn9y5q4w9zc2a58lc6acjvh7kqp-libgee-0.20.6-dev/include/gee-0.8 -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/gio-unix-2.0 -I/nix/store/ndy4ig7bc5y72mgpp2qmdik66kmz0dl6-granite-6.2.0-dev/include/granite -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -w '-DGETTEXT_PACKAGE="com.github.davidmhewitt.torrential"' -pthread -MD -MQ src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListRow.c.o -MF src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListRow.c.o.d -o src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListRow.c.o -c src/com.github.davidmhewitt.torrential.p/Widgets/TorrentListRow.c
In file included from /nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/transmission.h:23,
                 from src/com.github.davidmhewitt.torrential.p/Widgets/TorrentListRow.c:31:
/nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/tr-macros.h:8:10: fatal error: array: No such file or directory
    8 | #include <array>
      |          ^~~~~~~
compilation terminated.
[18/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_FileSelectTreeView.c.o
FAILED: src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_FileSelectTreeView.c.o 
gcc -Isrc/com.github.davidmhewitt.torrential.p -Isrc -I../src -Idata -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/glib-2.0 -I/nix/store/jzh15bi6zablx3d9s928w3lgqy6and91-glib-2.74.3/lib/glib-2.0/include -I/nix/store/yb0miyl7hgl9jcrni8qhykdaa747si35-gtk+3-3.24.36-dev/include/gtk-3.0 -I/nix/store/4zh493xqn3zmbbp2769xr6lr1klii7ff-at-spi2-core-2.46.0-dev/include/atk-1.0 -I/nix/store/mvhiwg7wkacdmi6p6j1sb3sm4ww3mq6z-cairo-1.16.0-dev/include/cairo -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include/freetype2 -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include -I/nix/store/ckd2dal5674yjgwdcf0lpqyxn19g4mdk-gdk-pixbuf-2.42.10-dev/include/gdk-pixbuf-2.0 -I/nix/store/vffghgqfw7md3jg7qclnbfy2afzri65l-pango-1.50.12-dev/include/pango-1.0 -I/nix/store/bd3x5n8mrmhz65c81xi8m669kixhgp7v-harfbuzz-6.0.0-dev/include/harfbuzz -I/nix/store/6v8jpxn9y5q4w9zc2a58lc6acjvh7kqp-libgee-0.20.6-dev/include/gee-0.8 -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/gio-unix-2.0 -I/nix/store/ndy4ig7bc5y72mgpp2qmdik66kmz0dl6-granite-6.2.0-dev/include/granite -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -w '-DGETTEXT_PACKAGE="com.github.davidmhewitt.torrential"' -pthread -MD -MQ src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_FileSelectTreeView.c.o -MF src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_FileSelectTreeView.c.o.d -o src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_FileSelectTreeView.c.o -c src/com.github.davidmhewitt.torrential.p/Widgets/FileSelectTreeView.c
In file included from /nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/transmission.h:23,
                 from src/com.github.davidmhewitt.torrential.p/Widgets/FileSelectTreeView.c:31:
/nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/tr-macros.h:8:10: fatal error: array: No such file or directory
    8 | #include <array>
      |          ^~~~~~~
compilation terminated.
[19/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_MainWindow.c.o
FAILED: src/com.github.davidmhewitt.torrential.p/meson-generated_MainWindow.c.o 
gcc -Isrc/com.github.davidmhewitt.torrential.p -Isrc -I../src -Idata -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/glib-2.0 -I/nix/store/jzh15bi6zablx3d9s928w3lgqy6and91-glib-2.74.3/lib/glib-2.0/include -I/nix/store/yb0miyl7hgl9jcrni8qhykdaa747si35-gtk+3-3.24.36-dev/include/gtk-3.0 -I/nix/store/4zh493xqn3zmbbp2769xr6lr1klii7ff-at-spi2-core-2.46.0-dev/include/atk-1.0 -I/nix/store/mvhiwg7wkacdmi6p6j1sb3sm4ww3mq6z-cairo-1.16.0-dev/include/cairo -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include/freetype2 -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include -I/nix/store/ckd2dal5674yjgwdcf0lpqyxn19g4mdk-gdk-pixbuf-2.42.10-dev/include/gdk-pixbuf-2.0 -I/nix/store/vffghgqfw7md3jg7qclnbfy2afzri65l-pango-1.50.12-dev/include/pango-1.0 -I/nix/store/bd3x5n8mrmhz65c81xi8m669kixhgp7v-harfbuzz-6.0.0-dev/include/harfbuzz -I/nix/store/6v8jpxn9y5q4w9zc2a58lc6acjvh7kqp-libgee-0.20.6-dev/include/gee-0.8 -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/gio-unix-2.0 -I/nix/store/ndy4ig7bc5y72mgpp2qmdik66kmz0dl6-granite-6.2.0-dev/include/granite -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -w '-DGETTEXT_PACKAGE="com.github.davidmhewitt.torrential"' -pthread -MD -MQ src/com.github.davidmhewitt.torrential.p/meson-generated_MainWindow.c.o -MF src/com.github.davidmhewitt.torrential.p/meson-generated_MainWindow.c.o.d -o src/com.github.davidmhewitt.torrential.p/meson-generated_MainWindow.c.o -c src/com.github.davidmhewitt.torrential.p/MainWindow.c
In file included from /nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/transmission.h:23,
                 from src/com.github.davidmhewitt.torrential.p/MainWindow.c:37:
/nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/tr-macros.h:8:10: fatal error: array: No such file or directory
    8 | #include <array>
      |          ^~~~~~~
compilation terminated.
[20/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Dialogs_FileSelectDialog.c.o
FAILED: src/com.github.davidmhewitt.torrential.p/meson-generated_Dialogs_FileSelectDialog.c.o 
gcc -Isrc/com.github.davidmhewitt.torrential.p -Isrc -I../src -Idata -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/glib-2.0 -I/nix/store/jzh15bi6zablx3d9s928w3lgqy6and91-glib-2.74.3/lib/glib-2.0/include -I/nix/store/yb0miyl7hgl9jcrni8qhykdaa747si35-gtk+3-3.24.36-dev/include/gtk-3.0 -I/nix/store/4zh493xqn3zmbbp2769xr6lr1klii7ff-at-spi2-core-2.46.0-dev/include/atk-1.0 -I/nix/store/mvhiwg7wkacdmi6p6j1sb3sm4ww3mq6z-cairo-1.16.0-dev/include/cairo -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include/freetype2 -I/nix/store/ag35f2gsrl7j8paxdcv2jhr6h35h2n10-freetype-2.12.1-dev/include -I/nix/store/ckd2dal5674yjgwdcf0lpqyxn19g4mdk-gdk-pixbuf-2.42.10-dev/include/gdk-pixbuf-2.0 -I/nix/store/vffghgqfw7md3jg7qclnbfy2afzri65l-pango-1.50.12-dev/include/pango-1.0 -I/nix/store/bd3x5n8mrmhz65c81xi8m669kixhgp7v-harfbuzz-6.0.0-dev/include/harfbuzz -I/nix/store/6v8jpxn9y5q4w9zc2a58lc6acjvh7kqp-libgee-0.20.6-dev/include/gee-0.8 -I/nix/store/qxfdxjwd1n8izbn5csg6bm925zfzibhv-glib-2.74.3-dev/include/gio-unix-2.0 -I/nix/store/ndy4ig7bc5y72mgpp2qmdik66kmz0dl6-granite-6.2.0-dev/include/granite -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -w '-DGETTEXT_PACKAGE="com.github.davidmhewitt.torrential"' -pthread -MD -MQ src/com.github.davidmhewitt.torrential.p/meson-generated_Dialogs_FileSelectDialog.c.o -MF src/com.github.davidmhewitt.torrential.p/meson-generated_Dialogs_FileSelectDialog.c.o.d -o src/com.github.davidmhewitt.torrential.p/meson-generated_Dialogs_FileSelectDialog.c.o -c src/com.github.davidmhewitt.torrential.p/Dialogs/FileSelectDialog.c
In file included from /nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/transmission.h:23,
                 from src/com.github.davidmhewitt.torrential.p/Dialogs/FileSelectDialog.c:32:
/nix/store/1zmnbjj2ip64dpras97aagyb42gvk62v-transmission-4.0.0/include/transmission/tr-macros.h:8:10: fatal error: array: No such file or directory
    8 | #include <array>
      |          ^~~~~~~
compilation terminated.
[21/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_MultiInfoBar.c.o
[22/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Application.c.o
[23/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_PreferencesWindow.c.o
[24/29] Compiling C object src/com.github.davidmhewitt.torrential.p/meson-generated_Widgets_TorrentListBox.c.o
ninja: build stopped: subcommand failed.
```

</details>

Unfortunately I have no idea how to fix the build :disappointed: transmission 4.0.0 "[migrated from C90 to C++](https://github.com/transmission/transmission/releases/tag/4.0.0)", probably C++ APIs are now used in public libtransmission headers. Vala bindings probably [don't work well with C++ libraries](https://wiki.gnome.org/Projects/Vala/ManualBindings#Prerequisites) I guess?

**Comment by davidmhewitt** [comment]
Yes, your assessment is correct. This is because Vala can't bind to C++ APIs.

The maintainers of Transmission notified me that this would become a problem when 4.0 was released.

I need to do some significant refactoring or re-writing before this can be built against Transmission 4.0, which isn't going to happen for at least a couple of months.
